version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  flask-app:
    container_name: task-boilerplate
    image: app:latest
    build: ./app
    environment:
      PASSWORD: ${password}
  db:
    container_name: mysql
    image: db:latest
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${password}